dbt_martech_campaign_etl:
  outputs:
    dev:
      dataset: imdb_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "C:/Users/王泽/.dbt/service-account.json"
      location: US
      method: service-account
      priority: interactive
      project: the-field-448907-r6
      threads: 1
      type: bigquery
  target: dev

