version: 2

sources:
  - name: imdb_source  # Reference for original dataset
    database: the-field-448907-r6
    schema: imdb  # ✅ Keep this as it is since it's read-only
    tables:
      - name: title_basics
      - name: title_ratings
      - name: name_basics
      - name: title_akas
      - name: title_crew
      - name: title_episode
      - name: title_principals
      - name: reviews  # ✅ Ensure all 8 tables are included

  - name: dbt_models  # Where DBT will store models
    database: the-field-448907-r6
    schema: my_imdb  # ✅ This is the dataset where DBT will write models
    tables:
      - name: transformed_movies  # Add more tables if necessary
